site_name: Game Memo
theme:
  name: material
  palette:
    primary: black
  icon:
    logo: material_custom/sports_esports-white-18dp
  custom_dir: overrides
  favicon: favicon.ico

extra:
  search:
    language: 'en, ja'
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_x_neo_
    - icon: fontawesome/brands/github
      link: https://github.com/KazuyaMatsunaga
extra_css:
  - '//fonts.googleapis.com/earlyaccess/notosansjp.css'
  - '//fonts.googleapis.com/css?family=Open+Sans:600,800'
  - 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css'
markdown_extensions:
  - admonition
  - footnotes
  - fontawesome_markdown
  - pymdownx.keys
  - codehilite:
      use_pygments: true
      noclasses: true
      pygments_style: vim
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true